spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.datasource.driver-class-name=com.impossibl.postgres.jdbc.PGDriver
spring.datasource.url=jdbc:pgsql://db:5432/workdist
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.validationQuery=SELECT 1

spring.jpa.properties.hibernate.show_sql=true

logging.level.root=WARN
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.com.example=DEBUG
logging.level.org.flywaydb=INFO
logging.level.org.hibernate=INFO

spring.output.ansi.enabled=always

management.trace.http.enabled=true
management.endpoints.web.exposure.include=httptrace